[package]
name = "ascii"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
video-rs = { version = "0.9", features = ["ndarray"] }

[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\mingw64\\bin\\gcc.exe"